version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb-server
    networks:
      - backend-net
    volumes:
      - todoapp:/data/db
  express-server:
    build:
      context: C:/dev/arseniy/apps/backend
      dockerfile: Dockerfile
    container_name: express-server
    networks:
      - backend-net
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb-server/todoapp
    volumes:
      - C:/dev/arsenyiy/apps/backend:/app

networks:
  backend-net:
    driver: bridge

volumes:
  todoapp:
