version: "3.8"
services:
  mongodb-server:
    image: mongo
    container_name: mongodb-server
    volumes:
      - todoapp:/data/db
    networks:
      - backend-net

  express-server:
    build:
      context: ../../
      dockerfile: ./apps/backend/Dockerfile
    container_name: express-server
    ports:
      - "5001:5000"
    env_file:
      - ./.env
    depends_on:
      - mongodb-server
    networks:
      - backend-net
    command: node main.js

networks:
  backend-net:
    driver: bridge

volumes:
  todoapp:
